#Application Server Port
server:
  port: 8089

#Application Server Name
spring:
  application:
    name: disl-assignment-one

#Application Database Setup
  datasource:
    url: jdbc:postgresql://ec2-3-231-82-226.compute-1.amazonaws.com:5432/d1gs192s2oflnj
    username: hxlehekcwxtgqe
    password: f3b4a78b9a073f137b069027586e4c390a264ffef98dd4bdf9d00aa3c96435f0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        #dialect: org.hibernate.dialect.MySQL8Dialect
        #generate_statistics: true
        jdbc:
          batch_size: 50
          order_inserts: true
    hibernate:
      ddl-auto: update
    show-sql: true

#OpenAPI Swagger-UI Custom Path
springdoc:
  swagger-ui:
    path: /documentation


